<?php
/** Language specific texts */

$langde = array('authors' => "Autoren",
	'author_details' => "Details Autor",
	'back' => "Zurück",
	'booksby' => "Bücher von",
	'booksbytag' => "Bücher mit Schlagwort",
	'book_details' => "Buchdetails",
	'check_access' => "Freischalten",
	'check_access_info' => "Diese Buch ist passwortgeschützt. Bitte freischalten, um es herunter zu laden.",
	'comment' => 'Beschreibung',
	'dl30' => "Die letzten 30",
	'download' => "Herunterladen",
	'error' => 'Fehler',
	'home' => "Start",
	'invalid_password' => "Ungültiges Passwort",
	'mdb_error' => 'Calibre Datenbank existiert nicht oder konnte nicht gelesen werden: ',
	'not_found1' => 'Nicht gefunden!',
	'not_found2' => 'Die angeforderte Ressource konnte nicht gefunden werden. Dies sollte eigentlich nicht passieren. Bitte prüfen Sie, ob ihre Calibre-Datenbank defekt ist.',
	'presskey' => 'Taste drücken, um das Buch im betreffenden Format herunter zu laden.',
	'published' => 'Veröffentlicht',
	'tags' => "Schlagwörter",
	'tag_details' => "Details Schlagwort",
	'titles' => "Bücher");
$langen = array('authors' => "Authors",
	'author_details' => "Author Details",
	'back' => "Back",
	'booksby' => "Books by",
	'booksbytag' => "Books tagged with",
	'book_details' => "Book Details",
	'check_access' => "Submit Password",
	'check_access_info' => "This book is protected. Please enter your password to enable the book download.",
	'comment' => 'Description',
	'dl30' => "Most recent 30",
	'download' => "Download",
	'error' => 'Error',
	'home' => "Home",
	'invalid_password' => "Invalid Password",
	'mdb_error' => 'Calibre database not found or not readable: ',
	'not_found1' => 'Not found!',
	'not_found2' => 'The requested ressource is no available. This should not happen. Please check your Calibre library for defects.',
	'presskey' => 'Press a button to download the book in the respective format.',
	'published' => 'Published',
	'tags' => "Tags",
	'tag_details' => "Tag Details",
	'titles' => "Books");

?>
