<?php
/** Language specific texts */

// German
$langde = array('admin' => 'Konfiguration',
	'admin_pw1' => 'Admin Passwort',
	'admin_pw2' => 'Admin Passwort',
	'admin_pw_expl' => 'Optional: Tragen sie hier ein Passwort ein, um den Zugang zu den Admin-Einstellungen einzuschränken.',
	'admin_pw_required1' => 'Fehlendes Admin-Passwort',
	'admin_pw_required2' => 'Sie wollen das Admin-Passwort für den Downloadschutz verwenden, haben aber kein gültiges Passwort eingetragen. Bitte tragen Sie eines ein.',
	'admin_short' => 'Admin',
	'authors' => 'Autoren',
	'author_details' => 'Details Autor',
	'back' => 'Zurück',
	'booksby' => 'Bücher von',
	'booksbytag' => 'Bücher mit Schlagwort',
	'book_details' => 'Buchdetails',
	'calibre_dir1' => 'Calibre Bibliotheksverzeichnis',
	'calibre_dir2' => 'Zum Beispiel: /volume1/books',
	'calibre_dir_expl' => 'Der Pfad zu ihrer Calibre-Bibliothek. Tragen sie hier den vollen Verzeichnisnamen ein.',
	'changes_saved' => 'Änderungen gespeichert',
	'check_access' => 'Freischalten',
	'check_access_info' => 'Diese Buch ist passwortgeschützt. Bitte freischalten, um es herunter zu laden.',
	'comment' => 'Beschreibung',
	'dl30' => 'Die letzten 30',
	'download' => 'Herunterladen',
	'error' => 'Fehler',
	'glob_dl_expl' => 'Wenn sie ihr Netz mit anderen Benutzern teilen, können sie hier den Passwort-Schutz fürs Herunterladen der Bücher aktivieren. Falls sie schon ein Admin-Passwort vergeben haben, kann das auch fürs Herunerladen genutzt werden. Oder sie erstellen einfach ein neues, separates Passwort.',
	'glob_dl_legend' => 'Herunterladen per Passwort schützen',
	'glob_dl_pw1' => 'Passwort fürs Herunterladen',
	'glob_dl_pw2' => 'Passwort fürs Herunterladen',	
	'glob_dl_radio1' => 'Nein, nicht nötig',	
	'glob_dl_radio2' => 'Ja, Admin-Passwort verwenden',
	'glob_dl_radio3' => 'Ja, anderes Passwort angeben (unten eingeben)',
	'home' => 'Start',
	'invalid_calibredir1' => 'Ungültiges Calibre-Verzeichnis',
	'invalid_calibredir2' => 'Auf das angegebene Calibre-Verzeichnis kann nicht zugegriffen werden. Ist es ein Calibre-Verzeichnis? Passen die Zugriffsrechte? Existiert das angegebene Verzeichnis?',
	'invalid_password' => 'Ungültiges Passwort',
	'invalid_password2' => 'Das eingegebene Passwort scheint ungültig zu sein. Bitte versuchen Sie es mit einem anderen.',
	'mdb_error' => 'Calibre Datenbank existiert nicht oder konnte nicht gelesen werden: ',
	'no_config' => 'config.php nicht gefunden oder fehlerhaft. Bitte kopieren Sie config.php.template nach config.php und nehmen Sie dort ihre Einstellungen vor.',
	'not_found1' => 'Nicht gefunden!',
	'not_found2' => 'Die angeforderte Ressource konnte nicht gefunden werden. Dies sollte eigentlich nicht passieren. Bitte prüfen Sie, ob ihre Calibre-Datenbank defekt ist.',
	'pagination_next' => 'vor',
	'pagination_page' => 'Seite',
	'pagination_prev' => 'zurück',
	'pagination_search' => 'Suche',
	'pagination_search_lbl' => 'Suchen',
	'pagination_search_ph' => 'Suchen ...',
	'presskey' => 'Taste drücken, um das Buch im betreffenden Format herunter zu laden.',
	'published' => 'Veröffentlicht',
	'save' => 'Speichern',
	'tags' => 'Schlagwörter',
	'tag_details' => 'Details Schlagwort',
	'titles' => 'Bücher',
	'unknown_error1' => 'Unbekannter Fehler',
	'unknown_error2' => 'Ein bisher unbekannter Fehler wurde gemeldet.',
	);

// English
$langen = array('admin' => 'Configuration',
	'admin_pw1' => 'Admin Password',
	'admin_pw2' => 'Admin Password',
	'admin_pw_expl' => 'Optional: Enter a password to protect the admin page from changes by others.',
	'admin_pw_required1' => 'No Admin password set',
	'admin_pw_required2' => 'You are trying to use the admin password for download protection without a valid admin password. Please enter a valid admin password.',
	'admin_short' => 'Admin',
	'authors' => 'Authors',
	'author_details' => 'Author Details',
	'back' => 'Back',
	'booksby' => 'Books by',
	'booksbytag' => 'Books tagged with',
	'book_details' => 'Book Details',
	'calibre_dir1' => 'Calibre library path',
	'calibre_dir2' => 'Example: /volume1/books',
	'calibre_dir_expl' => 'The path to your Calibre library. Please enter the full path/directory name.',
	'changes_saved' => 'Changes saved',
	'check_access' => 'Submit Password',
	'check_access_info' => 'This book is protected. Please enter your password to enable the book download.',
	'comment' => 'Description',
	'dl30' => 'Most recent 30',
	'download' => 'Download',
	'error' => 'Error',
	'glob_dl_expl' => 'If you are sharing your network with others you could activate a password protection for book downloads. If you already have an admin password you can reuse that, or simply specify a new, separate one.',
	'glob_dl_legend' => 'Protect downloads with a password',
	'glob_dl_pw1' => 'Password for downloads',
	'glob_dl_pw2' => 'Download password',
	'glob_dl_radio1' => 'No, not necessary',
	'glob_dl_radio2' => 'Yes, use admin password',
	'glob_dl_radio3' => 'Yes, use a separate password (enter below)',
	'home' => 'Home',
	'invalid_calibredir1' => 'Invalid Calibre directory',
	'invalid_calibredir2' => 'The configured Calibre directory cannot be used. Is it really a Calibre directory? Is it readable? Does it exist?',
	'invalid_password' => 'Invalid Password',
	'invalid_password2' => 'This password is not valid. Please use a different one.',
	'mdb_error' => 'Calibre database not found or not readable: ',
	'no_config' => 'config.php not found or in bad shape. Please copy config.php.template to config.php and make your configuration changes there.',
	'not_found1' => 'Not found!',
	'not_found2' => 'The requested ressource is not available. This should not happen. Please check your Calibre library for defects.',
	'pagination_next' => 'next',
	'pagination_page' => 'Page',
	'pagination_prev' => 'previous',
	'pagination_search' => 'Search',
	'pagination_search_lbl' => 'Search',
	'pagination_search_ph' => 'Search ...',
	'presskey' => 'Press a button to download the book in the respective format.',
	'published' => 'Published',
	'save' => 'Save',
	'tags' => 'Tags',
	'tag_details' => 'Tag Details',
	'titles' => 'Books',
	'unknown_error1' => 'Unknown Error',
	'unknown_error2' => 'An unknown error occured.',
	);

// French
$langfr = array('admin' => 'Configuration',
	'admin_pw1' => 'Mot de passe Administrateur',
	'admin_pw2' => 'Mot de passe Administrateur',
	'admin_pw_expl' => 'Option: Introduisez une mot de passe administrateur pour contrôler l\'accès à la configuration',
	'admin_pw_required1' => 'Pas de mot de passe admin défini',
	'admin_pw_required2' => 'Vous essayez d\'utilizer le mot de passe admin pour télécharger des livres protégés par un mot de passe. Utilisez le bon mot de passe.',
	'admin_short' => 'Admin',
	'authors' => 'Auteurs',
	'author_details' => 'Détails auteurs',
	'back' => 'Retour',
	'booksby' => 'Livres par',
	'booksbytag' => 'Livres par tag',
	'book_details' => 'Détails des livres',
	'calibre_dir1' => 'Chemin vers le répertoire Calibre',
	'calibre_dir2' => 'Exemple: /volume1/books',
	'calibre_dir_expl' => 'Le chemin vers votre répertoire où se trouve votre bibliothèque Calibre. Introduisez un nom complet chemin/nom_répertoire',
	'changes_saved' => 'Changements sauvegardés',
	'check_access' => 'Soumettre un mot de passe',
	'check_access_info' => 'Ce livre est protégé. Introduisez le mot de passe pour télécharger le livre.',
	'comment' => 'Description',
	'dl30' => 'Les 30 plus récents livres',
	'download' => 'Télécharger',
	'error' => 'Erreur',
	'glob_dl_expl' => 'Si vous votre réseau est ouvert au public, vous pouvez activer un mot de passe pour protéger le téléchargement de vos livres. Si vous avez déjà un mot de passe administrateur, vous pouvez le réutiliser ou en définir un nouveau, différent.',
	'glob_dl_legend' => 'Protéger les téléchargements avec un mot de passe',
	'glob_dl_pw1' => 'Mot de passe pour les téléchargements',
	'glob_dl_pw2' => 'Mot de passe téléchargement',
	'glob_dl_radio1' => 'Non, pas nécessaire',
	'glob_dl_radio2' => 'Oui, utilisez le mot de passe admin',
	'glob_dl_radio3' => 'Oui, utilisez un mot de passe différent (introduisez-le plus bas)',
	'home' => 'Acceuil',
	'invalid_calibredir1' => 'Répertoire vers la bibliothèque Calibre invalide',
	'invalid_calibredir2' => 'La base de données Calibre configurée ne peut pas être utilisée. Est-ce le bon répertoire ? LEs droits d\'accès sont-ils corrects ?  Existe-t-elle ? ',
	'invalid_password' => 'Mot de passe invalide',
	'invalid_password2' => 'Ce mot de passe n\'est pas valide. Veuillez réessayer.',
	'mdb_error' => 'Base de données Calibre database non trouvée ou illisible: ',
	'no_config' => 'config.php n\'a pas étré trouvé ou n\'est pas bien formaté. Veuillez copier le fichier config.php.template vers config.php et refaire votre propre configuration.',
	'not_found1' => 'Non trouvé !',
	'not_found2' => 'La resource demandée n\'est pas disponible. Cela ne devrait pas se produire... Vérifier votre base de donnée Calibre.',

	'pagination_next' => 'suiv.',
	'pagination_page' => 'Page',
	'pagination_prev' => 'préc.',
	'pagination_search' => 'Recherche',
	'pagination_search_lbl' => 'Recherche',
	'pagination_search_ph_author' => 'Recherche ...',

	'presskey' => 'Cliquez sur le bouton pour télécharger le livre dans le format correspondant.',
	'published' => 'Publié',
	'save' => 'Sauver',
	'tags' => 'Tags',
	'tag_details' => 'Détails du Tag',
	'titles' => 'Livres',
	'unknown_error1' => 'Erreur inconnue',
	'unknown_error2' => 'Une erreur s\'est produite',
	);

?>
