<?php
/** Language specific texts */

$langde = array('admin' => 'Konfiguration',
	'admin_pw1' => 'Admin Passwort',
	'admin_pw2' => 'Admin Passwort',
	'admin_pw_expl' => 'Optional: Tragen sie hier ein Passwort ein, um den Zugang zu den Admin-Einstellungen einzuschränken.',
	'admin_pw_required1' => 'Fehlendes Admin-Passwort',
	'admin_pw_required2' => 'Sie wollen das Admin-Passwort für den Downloadschutz verwenden, haben aber kein gültiges Passwort eingetragen. Bitte tragen Sie eines ein.',
	'admin_short' => 'Admin',
	'authors' => "Autoren",
	'author_details' => "Details Autor",
	'back' => "Zurück",
	'booksby' => "Bücher von",
	'booksbytag' => "Bücher mit Schlagwort",
	'book_details' => "Buchdetails",
	'calibre_dir1' => 'Calibre Bibliotheksverzeichnis',
	'calibre_dir2' => 'Zum Beispiel: /volume1/books',
	'calibre_dir_expl' => 'Der Pfad zu ihrer Calibre-Bibliothek. Tragen sie hier den vollen Verzeichnisnamen ein.',
	'changes_saved' => 'Änderungen gespeichert',
	'check_access' => "Freischalten",
	'check_access_info' => "Diese Buch ist passwortgeschützt. Bitte freischalten, um es herunter zu laden.",
	'comment' => 'Beschreibung',
	'dl30' => "Die letzten 30",
	'download' => "Herunterladen",
	'error' => 'Fehler',
	'glob_dl_expl' => 'Wenn sie ihr Netz mit anderen Benutzern teilen, können sie hier den Passwort-Schutz fürs Herunterladen der Bücher aktivieren. Falls sie schon ein Admin-Passwort vergeben haben, kann das auch fürs Herunerladen genutzt werden. Oder sie erstellen einfach ein neues, separates Passwort.',
	'glob_dl_legend' => 'Herunterladen per Passwort schützen',
	'glob_dl_pw1' => 'Passwort fürs Herunterladen',
	'glob_dl_pw2' => 'Passwort fürs Herunterladen',	
	'glob_dl_radio1' => 'Nein, nicht nötig',	
	'glob_dl_radio2' => 'Ja, Admin-Passwort verwenden',
	'glob_dl_radio3' => 'Ja, anderes Passwort angeben (unten eingeben)',
	'home' => "Start",
	'invalid_calibredir1' => 'Ungültiges Calibre-Verzeichnis',
	'invalid_calibredir2' => 'Auf das angegebene Calibre-Verzeichnis kann nicht zugegriffen werden. Ist es ein Calibre-Verzeichnis? Passen die Zugriffsrechte? Existiert das angegebene Verzeichnis?',
	'invalid_password' => 'Ungültiges Passwort',
	'invalid_password2' => 'Das eingegebene Passwort scheint ungültig zu sein. Bitte versuchen Sie es mit einem anderen.',
	'mdb_error' => 'Calibre Datenbank existiert nicht oder konnte nicht gelesen werden: ',
	'no_config' => 'config.php nicht gefunden oder fehlerhaft. Bitte kopieren Sie config.php.template nach config.php und nehmen Sie dort ihre Einstellungen vor.',
	'not_found1' => 'Nicht gefunden!',
	'not_found2' => 'Die angeforderte Ressource konnte nicht gefunden werden. Dies sollte eigentlich nicht passieren. Bitte prüfen Sie, ob ihre Calibre-Datenbank defekt ist.',
	'presskey' => 'Taste drücken, um das Buch im betreffenden Format herunter zu laden.',
	'published' => 'Veröffentlicht',
	'save' => 'Speichern',
	'tags' => "Schlagwörter",
	'tag_details' => "Details Schlagwort",
	'titles' => "Bücher",
	'unknown_error1' => 'Unbekannter Fehler',
	'unknown_error2' => 'Ein bisher unbekannter Fehler wurde gemeldet.',
	);
$langen = array('admin' => 'Configuration',
	'admin_pw1' => 'Admin Password',
	'admin_pw2' => 'Admin Password',
	'admin_pw_expl' => 'Optional: Enter a password to protect the admin page from changes by others.',
	'admin_pw_required1' => 'No Admin password set',
	'admin_pw_required2' => 'You are trying to use the admin password for download protection without a valid admin password. Please enter a valid admin password.',
	'admin_short' => 'Admin',
	'authors' => "Authors",
	'author_details' => "Author Details",
	'back' => "Back",
	'booksby' => "Books by",
	'booksbytag' => "Books tagged with",
	'book_details' => "Book Details",
	'calibre_dir1' => 'Calibre library path',
	'calibre_dir2' => 'Example: /volume1/books',
	'calibre_dir_expl' => 'The path to your Calibre library. Please enter the full path/directory name.',
	'changes_saved' => 'Changes saved',
	'check_access' => "Submit Password",
	'check_access_info' => "This book is protected. Please enter your password to enable the book download.",
	'comment' => 'Description',
	'dl30' => "Most recent 30",
	'download' => "Download",
	'error' => 'Error',
	'glob_dl_expl' => 'If you are sharing your network with others you could activate a password protection for book downloads. If you already have a admin password you can reuse that, or simply specify a new, separate one.',
	'glob_dl_legend' => 'Protect downloads with a password',
	'glob_dl_pw1' => 'Password for downloads',
	'glob_dl_pw2' => 'Download password',
	'glob_dl_radio1' => 'No, not necessary',
	'glob_dl_radio2' => 'Yes, use admin password',
	'glob_dl_radio3' => 'Yes, use a seperate password (enter below)',
	'home' => "Home",
	'invalid_calibredir1' => 'Invalid Calibre directory',
	'invalid_calibredir2' => 'The configured Calibre directory cannot be used. Is it really a Calibre directory? Is ist readable? Does it exist?',
	'invalid_password' => "Invalid Password",
	'invalid_password2' => "This password is not valid. Please use a differnt one.",
	'mdb_error' => 'Calibre database not found or not readable: ',
	'no_config' => 'config.php not found or in bad shape. Please copy config.php.template to config.php and make your configuration changes there.',
	'not_found1' => 'Not found!',
	'not_found2' => 'The requested ressource is no available. This should not happen. Please check your Calibre library for defects.',
	'presskey' => 'Press a button to download the book in the respective format.',
	'published' => 'Published',
	'save' => 'Save',
	'tags' => "Tags",
	'tag_details' => "Tag Details",
	'titles' => "Books",
	'unknown_error1' => 'Unknown Error',
	'unknown_error2' => 'An unknown error ocuured.',

	);

?>
