const fs = require('fs');
const AdmZip = require('adm-zip');

const zip = new AdmZip();
zip.addLocalFolder("img", "img");
zip.addLocalFolder("js", "js", "/**/*.min.js");
zip.addLocalFile("js/libs/jquery.cookie.js", "js/libs/jquery.cookie.js");
zip.addLocalFile("js/script.js", "js/script.js");
zip.addLocalFolder("style/jquery", "style/jquery");
zip.addLocalFile("style/style.css", "style/");
zip.addLocalFolder("lib/BicBucStriim", "lib/BicBucStriim");
zip.addLocalFile("vendor/autoload.php", "vendor");
zip.addLocalFile("vendor/DateTimeFileWriter.php", "vendor");
zip.addLocalFile("vendor/epub.php", "vendor");
zip.addLocalFile("vendor/rb.php", "vendor");
zip.addLocalFolder("vendor/aura", "vendor/aura");
zip.addLocalFolder("vendor/composer", "vendor/composer");
zip.addLocalFolder("vendor/slim", "vendor/slim");
zip.addLocalFolder("vendor/twig", "vendor/twig");
zip.addLocalFolder("vendor/swiftmailer", "vendor/swiftmailer");
zip.addLocalFolder("vendor/ircmaxell", "vendor/ircmaxell");
zip.addLocalFolder("vendor/dflydev/markdown", "vendor/dflydev/markdown");
zip.addLocalFolder("templates", "templates");
zip.addLocalFolder("data", "data");
zip.addLocalFile("index.php");
zip.addLocalFile("installcheck.php");
zip.addLocalFile("favicon.ico");
zip.addLocalFile("bbs-icon.png");
zip.addLocalFile("CHANGELOG.md");
zip.addLocalFile(".htaccess");
zip.addLocalFile("NOTICE");
zip.addLocalFile("LICENSE");
zip.addLocalFile("README.md");
zip.writeZip("bicbucstriim.zip");
