const fs = require('fs');
const AdmZip = require('adm-zip');

const zip = new AdmZip();
zip.addLocalFolder("img", "img");
zip.addLocalFolder("js", "js", "/**/*.min.js");
zip.addLocalFile("js/libs/jquery.cookie.js", "js/libs/jquery.cookie.js");
zip.addLocalFile("js/script.js", "js/script.js");
zip.addLocalFolder("style/jquery", "style/jquery");
zip.addLocalFile("style/style.css", "style/style.css");
zip.addLocalFolder("lib/BicBucStriim", "lib/BicBucStriim");
zip.addLocalFolder("vendor", "vendor", "*.php");
zip.addLocalFolder("vendor/aura", "vendor/aura");
zip.addLocalFolder("vendor/composer", "vendor/composer");
zip.addLocalFolder("vendor/slim/slim", "vendor/slim/slim");
zip.addLocalFolder("vendor/slim/views/", "vendor/slim/views/");
zip.addLocalFolder("vendor/slim/slim/Slim", "vendor/slim/slim/Slim");
zip.addLocalFolder("vendor/twig/twig", "vendor/twig/twig");
zip.addLocalFolder("vendor/twig/twig/ext", "vendor/twig/twig/ext");
zip.addLocalFolder("vendor/twig/twig/lib", "vendor/twig/twig/lib");
zip.addLocalFolder("vendor/swiftmailer/swiftmailer/lib", "vendor/swiftmailer/swiftmailer/lib");
zip.addLocalFolder("vendor/swiftmailer/swiftmailer", "vendor/swiftmailer/swiftmailer");
zip.addLocalFolder("vendor/ircmaxell/password-compat/lib", "vendor/ircmaxell/password-compat/lib");
zip.addLocalFolder("vendor/dflydev/markdown/src", "vendor/dflydev/markdown/src");
zip.addLocalFolder("vendor/dflydev/markdown", "vendor/dflydev/markdown");
zip.addLocalFolder("templates", "templates");
zip.addLocalFolder("data", "data");
zip.addLocalFile("index.php");
zip.addLocalFile("installcheck.php");
zip.addLocalFile("favicon.ico");
zip.addLocalFile("bbs-icon.png");
zip.addLocalFile("CHANGELOG.md");
zip.addLocalFile(".htaccess");
zip.addLocalFile("NOTICE");
zip.addLocalFile("LICENSE");
zip.addLocalFile("README.md");
zip.writeZip("bicbucstriim.zip");
